### ISSUE TITLE
[FR] -  select a template directly  "On-Demand" Button without edit modus

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-ext-ondemand#145]
the end user (without Edit) can directly select the template and/or format for the OnDemand app.

can be also by a formula field with variables

**Comment by konne** [comment]
@AlexanderGoerlich please let us discuss this idea on the next meeting.

I like the idea to just make the format / template as expression so that this component still stay simple but the qlik designer get more possibilities to use third party extensions to enable more feature to the end-users

**Comment by AlexanderGoerlich** [comment]
and output format also
